global:
  resolve_timeout: 5m
#receivers:
#- name: prometheus-msteams
#  webhook_configs:
#  - url: "http://prometheus-msteams:2000/alertmanager"
#    send_resolved: true
route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 1h
  group_wait: 30s

  receiver: 'low_priority_receiver'  # default/fallback request handler
  routes:


    - receiver: high_priority_receiver
      match:
        severity: critical
      #continue: true  # https://stackoverflow.com/questions/62652927/prometheus-ms-teams-alert-manager

    - receiver: medium_priority_channel
      match:
        severity: medium
      #continue: true  # https://stackoverflow.com/questions/62652927/prometheus-ms-teams-alert-manager


    - receiver: low_priority_receiver
      match:
        severity: warning
      #continue: true  
    
receivers:
- name: 'high_priority_receiver'
  webhook_configs:
    - send_resolved: true
      url: 'http://prometheus-msteams:2000/high_priority_channel' # request handler 1

- name: 'medium_priority_channel'
  webhook_configs:
    - send_resolved: true
      url: 'http://prometheus-msteams:2000/medium_priority_channel' # request handler 3

- name: 'low_priority_receiver'
  webhook_configs:
    - send_resolved: true
      url: 'http://prometheus-msteams:2000/low_priority_channel' # request handler 2



 # receiver: prometheus-msteams
 # repeat_interval: 30m
 # routes:
 # - match:
 #     alertname: Watchdog
 #   receiver: prometheus-msteams

